### ISSUE TITLE
[WIP]Let's Encrypt使ってHTTPS対応 

### ISSUE THREAD

**Issue by bohebohe** [h5y1m141/life_with_beer#104]
## このIssueについて

issue #59 のPull Requestになります

### VagrantでのLet's Encriptの実行について

@hoyamada 
- [ ] 確認：VagrantでのLet's Encriptの実行は、Ubuntu 14.04 LTS VMのみ現在対応ですが、OSバージョンは大丈夫でしょうか？

- Ubuntu 14.04 LTS VM
http://letsencrypt.readthedocs.io/en/latest/contributing.html#vagrant

  -let’s encryptのssl証明書をvagrantのubuntuを使用して取得する | joppot https://joppot.info/2016/01/11/2784

- [ ] 課題確認：もしかすると公開サーバが必要な気がしている。DNS登録したマシンでの実行が必要か？
  - https://joppot.info/2016/01/11/2784
 - > `Let's Encrypt クライアントは、インターネットから当該ドメイン名にアクセスした際に接続されるサーバ（DNSのAレコードで指定されたIPアドレスのサーバ）で実行する必要があります。`
 - Dockerで作成したパターンを見たところ、「ポート80を開けておこう
PublicIPをなにかしらDNSで引けるようにしておこう」というのが作成サーバでの前提条件かもしれない。
http://qiita.com/sawanoboly/items/9fdde1707de5e975dd15

この場合、公開サーバ（さくら）での直接取得となってくるので、作業内容がちょっと異なってくる
その他に必要な作業を現状は列挙する。
- [ ] Ansibleの使い方を調べる
- [ ] 最初にlife_with_beer/provision/roles配下にlets_encryptディレクトリを作って必要な設定ファイルを作成する

**Comment by h5y1m141** [comment]
@bohebohe 

> VagrantでのLet's Encriptの実行は、Ubuntu 14.04 LTS VMのみ現在対応ですが、OSバージョンは大丈夫でしょうか？

あ・・・そうなんですね^^;

テスト用のVagrant環境＋本番のさくらVPSともにCentOS7.1なんでそうなると事前にVagrant環境で検証っていうシナリオは成り立たないので、ひとまずこのIssueクローズすることにします。

上記調べてもらった情報＋参考URLなどを見る限りこんな感じの作業になりそうですね

- [git cloneしてletsencryptをインストール](git clone https://github.com/letsencrypt/letsencrypt)
- Vagrant＋本番環境ともにNginx起動中でそっちで80番ポート使ってるので一旦**sudo systemctl stop nginx**で停止させる
- letsencryptクライアントを実行する
  - おそらくこの時にPublicIPをなにかしらDNSで引ける状態になってるのが前提

もしもAnsible使って構成するとすると

- life_with_beer/provision/roles/lets_encrypt/tasks/main.ymlを作成
- 上記ファイルに以下を記述

**Comment by h5y1m141** [comment]
Vagratnt環境での動作が確認難しいことがわかったのでこのIssueクローズします

**Comment by bohebohe** [comment]
共有ありがとうございます！
うちは、今回はLet's Encriptではなく、AWSでの証明書でやることになりました。
が、将来的にLet's Encriptは使う機会多そう。
