### ISSUE TITLE
動的に表示されるフォームを通じて記事が登録できる

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/life_with_beer#171]
## このIssueについて

#169 が完了したら着手してください

## Issueの完了条件

- [ ] 表示されるフォームで必要情報が入力されたら記事が登録できる
  - 最終的には画面遷移しない形を目指したいと思ってますが、今回のIssueでそこまで含めると大変かもしれないので、登録→完了の画面遷移してもOKです

**Comment by kaorina** [comment]
実装イメージ
1. View側のSubmitボタンをクリックするとJSを呼ぶ
2. JS側でフォームに入力された値を取得
3. AjaxでArticleController.ebのcreateアクションを呼ぶ（2の値をパラメータとしてどう渡すか？）[ここできるか要調査]
