### ISSUE TITLE
Let's Encrypt使ってHTTPS対応する

### ISSUE THREAD

**Issue by h5y1m141** [h5y1m141/life_with_beer#59]
## このIssueについて

SEOのことを考えて、無料のLet's Encryptを利用する形でサーバーはHTTPS対応したいと思ってます

## お願いしたいこと

Vagrant上でOKなので、Let's Encryptを利用したHTTPS対応の環境を自動的に構築できるようにしてもらいたいと思います

- [ ] [Let's Encrypt の使い方](https://letsencrypt.jp/usage/)あたりを参考にしてLet's Encryptを導入するまでに必要な作業をまとめる
  - インフラ構成はNginxを利用してるのでその場合に必要な作業に絞って情報まとめてもらえると助かります
- [ ] サーバーの構成管理にAnsibleを利用してるのでAnsibleの設定ファイルを作る
  - 最初にlife_with_beer/provision/roles配下にlets_encryptディレクトリを作る
  - 上記作成したディレクトリ下で必要な設定ファイルを作成する
  - 設定をする上で連絡先のメールアドレスなどが必要になりそうな気がしてるので、その場合は別途相談してください。

**Comment by bohebohe** [comment]
これ、こっちのプロジェクトでも対応予定なので、並行してやってみます。
Ansibleは経験ないのですが、Chefとpuppetで運用はしていたので、わかるかなと、
もし、急ぎで進捗がーということであればいってくださいー

**Comment by h5y1m141** [comment]
@bohebohe 

実は、お願い出来るんじゃないかなぁ〜と思ってました :smile: 

あー、そうだ。Gitの運用ルールをまとめておくべきでしたが、ひとまずこんな感じで考えてます

- git-flowで運用
  - [git-flowはこのあたりがイメージつくかも](http://qiita.com/KosukeSone/items/514dd24828b485c69a05)
  - Feature branch作る時には、issueのIDと紐付ける形にする
  - 今回の場合だと以下のようにgit-flowコマンドで対応してもらえればOKです

```sh
git-flow feature start ISSUE-59
```

ひとまず最初にWIPのPR作ってもらってこまめに更新してもらう形にしてもらうとありがたいです

WIPのPR使った作業フローは[こういうやつ](http://qiita.com/numa08/items/b676e38e3dbabfd39d18)
